### PÚBLICAS ###

### Prueba de vida
get http://localhost:3000/api/v1

### Signup - Crear nuevo usuario
POST http://localhost:3000/api/v1/signup
Content-Type: application/json

{
  "name": "Hons",
  "email": "test@example.com",
  "password": "123456"
}

### Login y guardar token
POST http://localhost:3000/api/v1/login
Content-Type: application/json

{
  "email": "homero1@example.com",
  "password": "123456"
}

### USER - RUTAS PRIVADAS ###

### Obtener todos los usuarios (ruta privada)
GET http://localhost:3000/api/v1/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4ZGIxYjE2OTY3MzMxMWZmNDY1ODI3NSIsImVtYWlsIjoiaG9tZXJvMUBleGFtcGxlLmNvbSIsImlhdCI6MTc1OTc5NDAxM30.VXNyyn-HZeCo60gXBdqNTDDtezEGMtMebIURewj3rWY

### upgrade user plan

PATCH http://localhost:3000/api/v1/users/plan/68db1b169673311ff4658275
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4ZGIxYjE2OTY3MzMxMWZmNDY1ODI3NSIsImVtYWlsIjoiaG9tZXJvMUBleGFtcGxlLmNvbSIsImlhdCI6MTc1OTY2NjU0OX0.abf1JgwwTySdLbbC_2zcwCc3bh5v72cHhxKD_pBiEpE
Content-Type: application/json

{
  "email": "homero1@example.com",
  "password": "123456"
}


### PROYECTOS
### Crear un nuevo proyecto
POST http://localhost:3000/api/v1/projects
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4ZGIxYWI5NzBhOGE3ZGE0YjllNjM5NSIsImVtYWlsIjoiaG9tZXJvQGV4YW1wbGUuY29tIiwiaWF0IjoxNzU5MTkyMDQ5fQ.LQIskKxAFjJ2gJwFbRbA65VGp-KA6WRmownIybUSjEQ
Content-Type: application/json

{
    "name": "Proyecto Obligatorio",
    "description": "Proyecto para la materia FullStack nuevo",
    "category": "Desarrollo",
    "owner": "68db1ab970a8a7da4b9e6395"
}
### TASKS - RUTAS PRIVADAS ###

### crear una tarea
POST http://localhost:3000/api/v1/tasks 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4ZGIxYWI5NzBhOGE3ZGE0YjllNjM5NSIsImVtYWlsIjoiaG9tZXJvQGV4YW1wbGUuY29tIiwiaWF0IjoxNzU5MTkyNjIxfQ.XIT-KWNQm0EhT5dOcwGee3y24R3D2X2ruzkn_6aZgIQ
Content-Type: application/json

{
  "title": "Nueva tarea Pablo",
  "description": "Descripción de la tarea, creada por pablo para testear el middleware",
  "assignedTo": "68db1ab970a8a7da4b9e6395",
  "projectId": "68db2a50bd36261bd5ce5f06" 
}

### Obtener todas las tareas del usuario logueado y proyecto.
GET http://localhost:3000/api/v1/tasks/project/68db2a50bd36261bd5ce5f06
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4ZGIxYjE2OTY3MzMxMWZmNDY1ODI3NSIsImVtYWlsIjoiaG9tZXJvMUBleGFtcGxlLmNvbSIsImlhdCI6MTc1OTE5NjU5OH0.o0tWgreO2r5ZUQdiu0I83tZYErO17epIOJssrz9UO3Q


### Borrar una tarea
DELETE http://localhost:3000/api/v1/tasks/68db283065f7edc6bfe2eb0d
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4ZGIxYWI5NzBhOGE3ZGE0YjllNjM5NSIsImVtYWlsIjoiaG9tZXJvQGV4YW1wbGUuY29tIiwiaWF0IjoxNzU5MTkyNjIxfQ.XIT-KWNQm0EhT5dOcwGee3y24R3D2X2ruzkn_6aZgIQ

### Obtener una tarea especifica 
get http://localhost:3000/api/v1/tasks/68db283065f7edc6bfe2eb0d
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4ZDM0NDUxMjdjOGExMDg5ZGM0NWQ3YSIsImVtYWlsIjoiaG9tZXJvOUBleGFtcGxlLmNvbSIsImlhdCI6MTc1ODY3NjM1OH0.9PT3vbZL6rPeOXtbp-nOw8vWaQiiBujp6AzY3tGeJcw


### Obtener las categorias de tasks
GET http://localhost:3000/api/v1/tasks/categories
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4ZGIxYWI5NzBhOGE3ZGE0YjllNjM5NSIsImVtYWlsIjoiaG9tZXJvQGV4YW1wbGUuY29tIiwiaWF0IjoxNzU5MTkyNjIxfQ.XIT-KWNQm0EhT5dOcwGee3y24R3D2X2ruzkn_6aZgIQ
