### Login y guardar token
POST http://localhost:3000/api/v1/login
Content-Type: application/json

{
  "email": "testuser@ort.com",
  "password": "123456"
}

### crear una tarea
POST http://localhost:3000/api/v1/tasks 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4ZGIxYjE2OTY3MzMxMWZmNDY1ODI3NSIsImVtYWlsIjoiaG9tZXJvMUBleGFtcGxlLmNvbSIsInRpcG9Vc3VhcmlvIjoidXNlciIsImlhdCI6MTc1OTc5NTk4MH0.lCal9heIu69tLtWHk0RYZp6XZmeeVx0UC85l9gqjLzM
Content-Type: application/json

{
  "title": "Nueva tarea Pablo",
  "description": "Descripción de la tarea, creada por pablo para testear el middleware",
  "assignedTo": "68db1b169673311ff4658275",
  "projectId": "68db2a50bd36261bd5ce5f06" 
}

### Borrar una tarea
DELETE http://localhost:3000/api/v1/tasks/68e45beb2bd82ed7bf46b360
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4ZTQ0YzdmMGE3MWMyMTY5ZTMyMmZkMSIsImVtYWlsIjoidGVzdHVzZXJAb3J0LmNvbSIsInRpcG9Vc3VhcmlvIjoiYWRtaW4iLCJpYXQiOjE3NTk3OTY5MzR9.elfG49rWos_hxqzp9Yrix5yBXH4gcl8qnInZZjVMke4

### Obtener todos los usuarios (ruta privada)
GET http://localhost:3000/api/v1/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4ZGIxYjE2OTY3MzMxMWZmNDY1ODI3NSIsImVtYWlsIjoiaG9tZXJvMUBleGFtcGxlLmNvbSIsImlhdCI6MTc1OTc5NDAxM30.VXNyyn-HZeCo60gXBdqNTDDtezEGMtMebIURewj3rWY
